import {combineReducers} from 'redux';
import {newCall,newCallTomorrow,listCalls,listTomorrowCalls,markCallDone,markCallUndone,deleteCall,listCallDone,dropCall,undropCall} from '../reducers/callReducer';
import {newTodo,newTodosTomorrow,listTodosTomorrow,listTodos,markTodoDone,markTodoUndone,deleteTodo,listDoneTodo,dropTodo,undropTodo} from '../reducers/todoReducer';
import {newGoto,newGotoTomorrow,listGotos,listGotosTomorrow,markGotoDone,markGotoUndone,deleteGoto,listDoneGoto,dropGoto,undropGoto} from '../reducers/gotoReducer';
import {newBuy,newTomorrowBuy,listBuys,listTomorrowBuy,markBuyDone,markBuyUndone,deleteBuy,listDoneBuy,dropBuy,undropBuy} from '../reducers/buyReducer';
import {newVisit,newTomorrowVisit,listVisits,listTomorrowVisit,markVisitDone,markVisitUndone,deleteVisit,listDoneVisit,dropVisit,undropVisit} from '../reducers/visitReducer';
import {newStudy,newTomorrowStudy,listStudys,listTomorrowStudys,markStudyDone,markStudyUndone,deleteStudy,listDoneStudy} from '../reducers/studyReducer';
import {newProject,newTomorrowProject,listProjects,listTomorrowProjects,markProjectDone,markProjectUndone,deleteProject,listDoneProject} from '../reducers/projectReducer';
import {newDaily,listDailys,markDailyDone,markDailyUndone,deleteDaily,listDoneDaily,dropCallTask,undropCallTask} from '../reducers/dailyReducer';

export default combineReducers({
    newCall,
    newCallTomorrow,
    listCalls,
    listTomorrowCalls,
    markCallDone,
    markCallUndone,
    deleteCall,
    listCallDone,
    dropCall,
    undropCall,
    newTodo,
    newTodosTomorrow,
    listTodos,
    listTodosTomorrow,
    markTodoDone,
    markTodoUndone,
    deleteTodo,
    listDoneTodo,
    dropTodo,
    newGoto,
    newGotoTomorrow,
    listGotos,
    listGotosTomorrow,
    markGotoDone,
    markGotoUndone,
    deleteGoto,
    listDoneGoto,
    dropGoto,
    undropGoto,
    newBuy,
    newTomorrowBuy,
    listBuys,
    listTomorrowBuy,
    markBuyDone,
    markBuyUndone,
    deleteBuy,
    listDoneBuy,
    dropBuy,
    undropBuy,
    newVisit,
    newTomorrowVisit,
    listVisits,
    listTomorrowVisit,
    markVisitDone,
    markVisitUndone,
    deleteVisit,
    listDoneVisit,
    dropVisit,
    undropVisit,
    newStudy,
    newTomorrowStudy,
    listStudys,
    deleteStudy,
    listTomorrowStudys,
    markStudyDone,
    markStudyUndone,
    listDoneStudy,
    newProject,
    newTomorrowProject,
    listProjects,
    listTomorrowProjects,
    markProjectDone,
    markProjectUndone,
    deleteProject,
    listDoneProject,
    newDaily,
    listDailys,
    markDailyDone,
    markDailyUndone,
    deleteDaily,
    listDoneDaily,
    dropCallTask,
    undropCallTask
});